In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv('./train.csv')
if(df.isna().any().any()):
    print("Yes")
df.head()

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [3]:
y=df.iloc[:,0].values
X=df.drop(['label'],axis=1)

In [4]:
X.shape,y.shape

((42000, 784), (42000,))

In [5]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X=scaler.fit_transform(X)
print(X[:2,:])

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

In [6]:
from sklearn.decomposition import PCA
pca = PCA(n_components=200)
X_copy=pca.fit_transform(X)
print(pca.explained_variance_ratio_)

[0.05747953 0.04111691 0.03782867 0.02939862 0.02556439 0.02229844
 0.01952552 0.01771605 0.0156266  0.01424956 0.01361009 0.01222541
 0.01135736 0.0111309  0.01050311 0.01012326 0.00951303 0.00934514
 0.00907259 0.00885327 0.00838907 0.00812027 0.00775161 0.00752312
 0.0072769  0.00698756 0.00690455 0.00664924 0.00630675 0.00616301
 0.00610922 0.00597037 0.00577284 0.00573682 0.00564822 0.00546322
 0.0053943  0.00524361 0.00504843 0.0048853  0.00482244 0.00475901
 0.00460007 0.00457628 0.00449584 0.00446722 0.00443837 0.00436837
 0.00432712 0.00427027 0.00419269 0.00412179 0.0040246  0.00399433
 0.0039489  0.00390804 0.00379897 0.00372452 0.0036841  0.00365721
 0.00353276 0.00351086 0.00345411 0.00341391 0.00337779 0.00336474
 0.00331705 0.00329723 0.00320013 0.00316773 0.00312691 0.00311856
 0.00308208 0.00303269 0.00301506 0.00297131 0.00294843 0.00293622
 0.00287836 0.00286896 0.00283159 0.00282872 0.00281695 0.00279197
 0.00276832 0.00276304 0.00273907 0.00271798 0.00268128 0.00265434
 0.00262055 0.00260146 0.00258181 0.00254869 0.00253469 0.00252367
 0.00250038 0.00245738 0.00244336 0.00241349 0.00237621 0.00236167
 0.00232277 0.00230163 0.00229456 0.00226417 0.00224915 0.0022362
 0.00220665 0.00220131 0.00216741 0.00214639 0.00211096 0.0020984
 0.00204781 0.0020389  0.00201809 0.00200157 0.00196866 0.00195601
 0.00194187 0.00191568 0.00190217 0.00189951 0.00189316 0.00185077
 0.00184209 0.00182466 0.00179502 0.00179026 0.00177346 0.00175767
 0.00173557 0.00173038 0.00171786 0.00168023 0.00167543 0.00166144
 0.00163783 0.00162772 0.00160981 0.00160289 0.00159204 0.00157481
 0.00155694 0.00155052 0.00153455 0.00152152 0.00151657 0.00149361
 0.00148207 0.00147176 0.00146806 0.00146276 0.00144957 0.00143974
 0.00142737 0.00141359 0.00140779 0.00140565 0.00140328 0.00139837
 0.0013936  0.0013854  0.00137519 0.00136742 0.00136525 0.00135747
 0.00134806 0.00133128 0.00133005 0.00131358 0.00130911 0.00129183
 0.00128667 0.00126443 0.00126071 0.00125458 0.00124799 0.00124187
 0.00122886 0.00122015 0.00120821 0.00120281 0.00118526 0.00115434
 0.00115035 0.00114466 0.0011341  0.00112265 0.00110646 0.00109934
 0.00107298 0.00106568 0.00105811 0.0010296  0.00102075 0.00101113
 0.00100432 0.00099372]

In [7]:
pca.explained_variance_ratio_.sum()

0.8722391903840747

In [8]:
from sklearn.svm import SVC
svc=SVC(C=8,kernel='rbf',gamma=0.002)
svc.fit(X_copy,y)

SVC(C=8, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.002, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [9]:
X_test=pd.read_csv('./test.csv')
X_test.head()

,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [10]:
X_test=scaler.transform(X_test)
X_test=pca.transform(X_test)
output=svc.predict(X_test)

In [11]:
import csv
with open('output.csv','w',newline='') as f:
    field=['ImageId','Label']
    writer=csv.DictWriter(f,fieldnames=field)
    writer.writeheader()
    for i in range(len(X_test)):
        writer.writerow({'ImageId':i+1,'Label':output[i]})